---
title: "An Bui Community Analysis"
author: "sbsambado"
date: "3/27/2020"
output: html_document
---
More details regarding ordination and visualization can be found [here](http://rpubs.com/an-bui/553683).

```{r}
# libraries
library(tidyverse)
library(vegan)

# data

library(readr)
birds<- read_csv("~/Desktop/R Script/vegan/bird-comm.csv")%>% 
column_to_rownames("site")



# environmental variables
env <- read_csv("~/Desktop/env-var.csv")


# set up a "metadata" frame - will be useful for plotting later!
site_type <- env %>% 
  # selects the named columns
  select(site, landtype)
```

### How speciose are my communities?

```{r species-richness}
#
#
sppr <- specnumber(birds)

#
sppr_aov <- aov(sppr ~ landtype, data = site_type)
summary(sppr_aov)
```

```{r species-richness-plot}
# 
sppr_df <- sppr %>% 
  # 
  enframe() %>% 
  # 
  full_join(site_type, by = c("name" = "site"))

sppr_plot <- ggplot(sppr_df, aes(x = landtype, y = value, color = landtype)) +
  geom_boxplot()
sppr_plot
```

### How diverse are my communities?

```{r shannon-diversity}
# 
shannondiv <- diversity(birds)

# try simpson's diversity

```

```{r shannon-diversity-plot}
shandiv_df <- shannondiv %>% 
  # 
  enframe() %>% 
  # 
  full_join(., site_type, by = c("name" = "site")) %>% 
  # 
  group_by(landtype) %>% 
  summarize(mean = mean(value))

shandiv_plot <- ggplot(shandiv_df, aes(x = landtype, y = mean, fill = landtype)) +
  geom_col()
shandiv_plot
```

### How different are my communities in species composition?

#### perMANOVA
```{r bird-permanova}
# 
bird_perm <- adonis(birds ~ landtype, data = env)
bird_perm
```

#### PCA

```{r bird-PCA}
# 
# 
birdPCA <- rda(birds)
birdPCA
# 

summary(birdPCA)
# 
# 

pcabiplot <- biplot(birdPCA)
# 
# 

# 
PCAscores <- as.data.frame(pcabiplot$sites) %>% 
  bind_cols(site_type, .)

PCAvect <- as.data.frame(pcabiplot$species)


PCA_plot <- ggplot(PCAscores) +
  geom_point(aes(x = PC1, y = PC2, color = landtype)) +
  geom_segment(data = PCAvect, aes(x = 0, y = 0, xend = PC1, yend = PC2), arrow = arrow(length = unit(0.2, "cm"))) +
  geom_text(data = PCAvect, aes(x = PC1, y = PC2, label = rownames(PCAvect)))

PCA_plot
```

#### NMDS

Non-metric Multidimensional Scaling

```{r bird-NMDS}
#
bird_NMDS <- metaMDS(birds)

bird_NMDS

nmdsplot <- plot(bird_NMDS)

stressplot(bird_NMDS)
```

```{r NMDS-plot}
# 
# 
nmds_df <- as_tibble(bird_NMDS$points) %>% 
  # 
  bind_cols(site_type, .)

nmds_plot <- ggplot(nmds_df, aes(x = MDS1, y = MDS2, color = landtype, shape = landtype)) +
  geom_point(size = 3, alpha = 0.8) +
  stat_ellipse()
nmds_plot
```

##### Things to consider about stress

```{r subsampled-NMDS}
sub <- birds[sample(nrow(birds), 20), ]
subNMDS <- metaMDS(sub)
stressplot(subNMDS)
```

### How is community structure related to specific environmental variables?

```{r bird-CCA}
# 
# 
# 
# 
birdCCA <- cca(birds ~ canopy_height + stems_ha + big_stem_bas, data = env)
birdCCA


```

```{r bird-CCA-plot}
ccaplot <- plot(birdCCA)

# 
ccavectors <- as.data.frame(ccaplot$biplot * 5.15)

# 
site_data <- as.data.frame(ccaplot$sites) %>% 
  bind_cols(site_type, .)

species_data <- as.data.frame(ccaplot$species)

cca_plot <- ggplot(site_data) +
  geom_point(aes(x = CCA1, y = CCA2, color = landtype), shape = 19) +
  geom_segment(data = ccavectors, aes(x = 0, y = 0, xend = CCA1, yend = CCA2), arrow = arrow(length = unit(0.2, "cm"))) +
  scale_x_continuous(limits = c(-10, 16)) +
  scale_y_continuous(limits = c(-3, 12)) +
  geom_point(data = species_data, aes(x = CCA1, y = CCA2), shape = 17, size = 2, color = "blue") +
  geom_text(data = ccavectors, aes(x = CCA1, y = CCA2, label = rownames(ccavectors)))
cca_plot
```


